### ISSUE TITLE
Update "check_wasm" to check callee WASM's having "_get_callable_points_properties"

### ISSUE THREAD

**Issue by loloicci** [Finschia/cosmwasm#300]
In static check, WASMs which can be called as a dynamic link callee should check it has `_get_callable_points_properties`.

So we should add this logic to `check_wasm`.

**Comment by loloicci** [comment]
It looks we can check a contract has callable point during

https://github.com/Finschia/cosmwasm/blob/ac1e18e57466cc86807f6bdbdbc2012d7f67632f/packages/vm/src/compatibility.rs#L136-L147

**Comment by dudong2** [comment]
I've tried several things, but I haven't found a way to check for an attribute like `callable_points` in the `check_wasm` function. Since it uses `wasm_code`, I don't think it's easy to check for it in the usual way, and it doesn't have a unique function name for functions that use callable_points.

https://github.com/Finschia/cosmwasm/blob/ac1e18e57466cc86807f6bdbdbc2012d7f67632f/packages/vm/src/compatibility.rs#L59-L68

**Comment by dudong2** [comment]
There are two ideas for how to check `_get_callable_points_properties`.
 
1. Check if the contract's code has #[callable_points].
For `wasm code`, which is the result of being converted to a wasm file via build, there is no trace of whether the original code had `#[callable_points]`. It also doesn't have any special functions created by it, which makes this method inappropriate.

2. Check if the contract is called as a callee of a dynamic_link.
Normally, access to a contract (query, execute, etc...) is done through [vm/src/call.rs](https://github.com/Finschia/cosmwasm/blob/main/packages/vm/src/calls.rs). However, for a contract that is called as a `callee of a dynamic link`, this path is not followed. Therefore, it is possible to check `_get_callable_points_properties` when the callable_point of the callee contract is called. 

However, since the initial idea of `check_wasm` is a `static check` on the contract, we need to discuss whether it makes sense to check at that time.

**Comment by dudong2** [comment]
The above suggestion was right. It was my trial and error due to my initial misunderstanding. Here are the results of my tests on the [exported_function_names](https://github.com/Finschia/cosmwasm/blob/ac1e18e57466cc86807f6bdbdbc2012d7f67632f/packages/vm/src/compatibility.rs#L137) function.
```
--> hackatom.wasm
instantiate
deallocate
query
execute
migrate
sudo
allocate
interface_version_8

--> simple-callee.wasm
succeed_readonly
allocate
_get_callable_points_properties
fail
requires_iterator
instantiate
deallocate
interface_version_8
execute
succeed
```
Taking a simple-callee contract that is called as a callee of a dynamic link as an example, the functions `succeed, succeedd_readonly, and fail`, which are functions belonging to callable_points, are additionally `exported`. I think this will allow me to determine if these are functions that can be called as callee. thanks.

**Comment by dudong2** [comment]
In addition to the features called through [vm/src/call.rs](https://github.com/Finschia/cosmwasm/blob/main/packages/vm/src/calls.rs)., there is a requires_iterator, interface_version_8. This is defined in https://github.com/Finschia/cosmwasm/blob/ac1e18e57466cc86807f6bdbdbc2012d7f67632f/packages/std/src/exports.rs#L32-L52
